### PR TITLE
ZF 3 forward compatibility

### PR DESCRIPTION
**Pull request by chris1312**
These changes enables users to user either ZF 2.5 or 3.0+ versions.

### CODE REVIEW

**Comment by chris1312** [comment]
@juriansluiman is there anything I should add to this pull request?

**Comment by juriansluiman** [comment]
@chris1312 since I am not active in the php community anymore, I am not used to daily check GitHub :) Also, I cannot check the code in a test env anymore. But the changes look good and all buttons are green, so I'll just assume everything keeps working after merge 👍

**Comment by chris1312** [comment]
Thanks a lot!
Could you also release it within v0.4.x?

**Comment by juriansluiman** [comment]
Mm, I don't have a setup with git (😬 ) at this moment. My workflow was to create a git tag (signed) with CLI, push to GH and then create a release attached to that tag. Let me see if there's another option.

**Pull request merged**
